### ISSUE TITLE
Support for Python <3.8?

### ISSUE THREAD

**Issue by pradyunsg** [brettcannon/mousebender#20]
Would y'all be open to supporting all non-EoL Python versions? That'd make it possible for pip to adopt this... eventually. :3

**Comment by d3r3kk** [comment]
This would mean >=3.5 [according to this article][py_ver_table] as of this moment, is that correct or is there a more definitive source?

I will defer to @brettcannon here but that should be doable I believe.

[py_ver_table]:https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions "Wikipedia entry: History of Python, Table of Versions"

**Comment by pradyunsg** [comment]
https://devguide.python.org/#status-of-python-branches

**Comment by brettcannon** [comment]
@pradyunsg so the long and short of it is the plan has always been to bring this into `packaging`, but I have been hesitant while we still require Python 2.7 support there (as that was the most painful part of writing `packaging.tags`). So we are totally happy to, but my question is when are we going to drop Python 2.7 in 'packaging'?

**Comment by pradyunsg** [comment]
The only reason packaging is python 2.7 compatible, is for pip. Once we drop support in pip, packaging's next release can (and knowing myself, likely will) be Python 3 only.

**Comment by pradyunsg** [comment]
As for when we drop support in pip... Well, that I'm still figuring out and I'm personally in favor or earlier than later.

**Comment by pradyunsg** [comment]
pip drops support in pip 21.0 -- so the pip codebase will be Python 3.6+ sometime after October 2020.

**Comment by brettcannon** [comment]
Then we can aim to make this usable upstream during the last quarter of CY 2020.

**Comment by pradyunsg** [comment]
Hurrah! ^>^
