### ISSUE TITLE
Support PEP 592: yanked

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/mousebender#23]
https://www.python.org/dev/peps/pep-0592/

**Comment by brettcannon** [comment]
> Links in the simple repository MAY have a data-yanked attribute which may have no value, or may have an arbitrary string as a value.

> The value of the data-yanked attribute, if present, is an arbitrary string that represents the reason for why the file has been yanked. Tools that process the simple repository API MAY surface this string to end users.

So it seems at minimum we should have a `yanked` attribute and it has a boolean that represents if the file is yanked. We _could_ expand it to say that `yanked` has a truthy value if it has been yanked and if it's not `True` then it's the reason the file was yanked. Another option is to keep `yanked` as a boolean and add a `yanked_reason` that's `None` by default, otherwise the reason if provided.

@d3r3kk you have an opinion?

**Comment by d3r3kk** [comment]
> @d3r3kk you have an opinion?

Typically I like to be super explicit about these things, so I'd default to 3.

However, if the rate of `yanked` items is going to be super low, I could be convinced that 2 makes sense. 

What would a Python developer expect here? As a C-ish developer I think 3. But Python minds are not as closed as mine can be, and 2 seems like a more appropriate solution _if the number of items is low_.

**Comment by brettcannon** [comment]
@d3r3kk I have a PR up for option 2 for you to see what it looks like. 😄 

As for the rate, no one knows as that PEP was _just_ approved the other week. I _suspect_ most people and tools will just do `if yanked` which will work for all options. It's just a question of how much do we care about the potential of people specifying the reason for yanking a file **and** people wanting to know that reason.

**Comment by d3r3kk** [comment]
I would say _we_ don't really care much about the reason, but we probably shouldn't force that apathy on anyone. So option 2 and 3 are equally reasonable I think. I am happy with your call on separating the two fields or leaving them as you have it, unless you can think of any way that the 'truthiness' could be affected by the content of that string.

**Comment by brettcannon** [comment]
@d3r3kk truthiness for strings is anything that isn't the empty string. And that won't come into play as the code is written such that a false value leads to `True`. But I can add a test for that.

**Comment by brettcannon** [comment]
Out of curiosity I have asked Twitter: https://twitter.com/brettsky/status/1255218714447880195.

**Comment by brettcannon** [comment]
@d3r3kk another option is making it `Optional[str]` or `str` and to provide a default string value if one isn't specified but `data-yanked` is set, e.g. `"<unknown>"`, `"<unspecified>"`, or `"<🤷‍♂️>"`. 😉

**Comment by brettcannon** [comment]
@d3r3kk my last suggestion on this is a tuple: `yanked: Tuple[bool, Optional[str]]`. You still get your discrete bits of data and I get my minimized number of attributes. Deal?
