### ISSUE TITLE
Feature suggestion: Filename parsing logic

### ISSUE THREAD

**Issue by uranusjr** [brettcannon/mousebender#24]
A part of me feels this is a natural extension to the simple API parser. Once links are collected from an index, the next thing would be to make sense of them—:

* Which files contain the version I want?
* Which wheel is best for my platform?
* Is there an sdist?

We need to parse the file name in order to answer these questions. Python already has all the tools once we are able to split the name in chunks, but AFAIK there is not an existing library that contains this parsing logic (pip has its internal implementation for sdist, and uses distlib to parse wheel names).

I can try implement the module if you think this is a good idea.

**Comment by brettcannon** [comment]
@uranusjr We went back and forth on this, actually. In the end, though, we purposefully left it out as there isn't a spec on how to parse sdist names, so the best we could do is wheels. Since we didn't want to have a partial solution where we left out sdists we chose to leave it out.

Now we could go with what [PEP 517 says](https://www.python.org/dev/peps/pep-0517/#source-distributions) and thus after stripping off `.zip` or `.tar.gz` do `name, _, version = filename.rpartition("-")`, but is this robust enough to rely on? Basically if we are going to support grouping by version I want to be right the first time and not have to change it (IOW this had better be what ends up in any PEP that standardizes sdists 😉 ).

**Comment by brettcannon** [comment]
And I already have an idea of how to structure this _when_ we do this (whether now or when I or someone else finally gets around to writing an sdist PEP).

**Comment by uranusjr** [comment]
Cool, sounds like you have most things covered. The only difficult part is definitely sdist.

> Now we could go with what [PEP 517 says](https://www.python.org/dev/peps/pep-0517/#source-distributions) and thus after stripping off `.zip` or `.tar.gz` do `name, _, version = filename.rpartition("-")`, but is this robust enough to rely on?

It is probably robust *enough*. The problem with sdist is that it enforeces neither normalised name nor normalised version, so in theory you can name the sdist as `foo-1-2.tar.gz` if the project `foo` has a version `1-2`. I don’t think any modern mainstream packaging tool does this (Setuptools started normalising since way back in 6.0), but you might have problems if you want to parse old artifacts.

pip implements I believe the most bullet-proof approach if you know the package name in advance (which is the case for the Simple API):

https://github.com/pypa/pip/blob/6a7bf9477681d133467740568e24a6382dc4e29c/src/pip/_internal/index/package_finder.py#L973-L1016

If you want to standardise sdist name, definitely mandate the packaging tool to use a PEP 440 version string. Traditionally sdist can also be zip, bz2, or xz, but this is also something no modern packaging tools do anymore, so maybe it’d be fine to mandate `.tar.gz` going forward.

**Comment by brettcannon** [comment]
Another option is we write the code for wheels now but future-proof it for when sdist names are standard, then support for sdists can just be slotted in appropriately when it becomes available.

**Comment by brettcannon** [comment]
FYI the discussion on file names of sdists is happening at https://discuss.python.org/t/pep-625-file-name-of-a-source-distribution/4686/.

**Comment by pfmoore** [comment]
> pip implements I believe the most bullet-proof approach if you know the package name in advance

I've been researching sdist names on PyPI, and there are some where this approach fails, but if you are a bit more aggressive than canonicalising (basically, strip all characters other than `a-zA-Z0-9`) you can still find the version. I don't know whether it's worth going that far, though. There are some *really* bad package names on PyPI...

**Comment by brettcannon** [comment]
@pfmoore thanks for the info and suggestion! I'm waiting for the sdist discussion to settle and seeing where it ends up before moving forward with anything.

**Comment by uranusjr** [comment]
Update: I created [packaging-dists](https://github.com/uranusjr/packaging-dists) a while ago to cover this.

**Comment by brettcannon** [comment]
'packaging' now does file name parsing.
