### ISSUE TITLE
Feature suggestion: Package finder

### ISSUE THREAD

**Issue by pfmoore** [brettcannon/mousebender#37]
I'm considering an API for "finder logic" - letting tools provide a package name and get back a list of files that are acceptable in the current environment. Something like the following:

```python
>>> from mousebender.finder import Finder, IndexSource
>>> finder = Finder()
>>> pypi = IndexSource(page_getter)
>>> finder.add_source(pypi)
>>> finder.find("pip")
```

Would this be a good fit for this project, or should it go somewhere else (possibly a new standalone project)?

**Comment by brettcannon** [comment]
Short answer: I don't know. 😄 

Thinking out loud, what @d3r3kk and I would like to see this project eventually become is an example of an installer that **only** follows standards and other packages implementing those standards and help identify package gaps in the ecosystem (i.e. simplified pip for a modern age to show what's possible with defined specs 😉 ). Now I will fully admit we have not had a serious conversation of maintenance and where we want to ultimately draw the line on things. For instance, the Simple API stuff should end up in 'packaging' (and our plan is it will as soon as 'packaging' drops its Python 2 support), so I have been viewing the current API as provisional and a testing ground before we upstream to 'packaging'. When that happens this project becomes nothing more than a CLI demo/dirt-simple installer.

For your specific suggestion to provide a high-level wrapper (that I would assume would build on #24 to smooth out the overall "get me a URL to download the best-fitting wheel" logic), it could go here as I don't see that going into 'packaging'. But we also haven't talked about whether we want mousebender to be a library in its own right long-term. And I'm not arguing against it, either; having a project which provides higher-level APIs that every installer would logically need would be useful to projects like pip or anyone else who wants to conceivably be crazy enough to want to write an installer. 😉 

So I'm going to tentatively say, "sure, it can go here" if @d3r3kk is okay with the idea that we will clearly orient this project to providing the high-level APIs necessary to do installations following packaging specs (in a sans-I/O manner, of course 😁 ) and we continue to try and push things upstream to other libraries where appropriate/possible. IOW this project provides the higher-level API that pip doesn't want to provide. 😉 

BTW, using the term "finder" is doing my head in thanks to what they are for importers. 😄  That doesn't mean it's the wrong name, though.

**Comment by brettcannon** [comment]
@pfmoore "sat down" with @d3r3kk and after discussing it we decided that we want to keep mousebender more as a driver of finding holes in the packaging ecosystem rather than a fully support, standalone library. Basically anything of great worth we might create here we would want to upstream as appropriate. So while we would love to get this project to the point that we can do a standards-compliant-only pip-lite, we currently have no plans to add this with PyPA.
