### ISSUE TITLE
Consider changing how the changelog is managed

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/mousebender#65]
Perhaps https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes ?

**Comment by brettcannon** [comment]
The automatic release notes from GitHub has worked well in other projects I work with, so I plan to go with that.

**Comment by brettcannon** [comment]
Use https://github.com/marketplace/actions/require-labels to require an appropriate classification label for a PR.

**Comment by brettcannon** [comment]
Should probably also add branch protection to require a PR for each change.

**Comment by d3r3kk** [comment]
> Use https://github.com/marketplace/actions/require-labels to require an appropriate classification label for a PR.

What do we want to use in the list of required labels?

The `impact-` series of labels?

What would I put on a PR that only affected the README?

What would I put on a PR that only affected the workflow for CI?

(I'm just guessing here, but `impact-project`?)
