### ISSUE TITLE
Is there any plan for a new release?

### ISSUE THREAD

**Issue by gmc444-b** [brettcannon/mousebender#72]
I'm trying to build a collection of open source packages for Python 3.11, and I'm finding `mousebender` useful for certain aspects, however the last release (2.0.0) is dependent on a downrev version of `packaging`, while what's in the project repo isn't.

Is there any plan for a new release, and if so, what would be the approximate timeline?

**Comment by brettcannon** [comment]
I'm currently teaching a friend Python by working with him to implement #71 (which will lead to a significant API change). My hope is the new version will be out before September.

**Comment by brettcannon** [comment]
https://pypi.org/project/mousebender/2022.0.0/
